### ISSUE TITLE
api error

### ISSUE THREAD

**Issue by Mvkbesteu** [HanaokaYuzu/Gemini-API#30] opened 2024-08-08 13:57 UTC
hi, so after using the library for a bit, out of nowhere it just errors out and cannot use it for either a few mins or 5-6 hours. i do not spam it or anything so i doubt is ratelimit but it could be something related to the cookies however refreshing them do not help at all. i didnt refresh them and they worked hours later, or i refreshed them and they didnt work untill hours later.

i get this in my logs:

 File "/home/gemi/idkenv/lib/python3.11/site-packages/gemini_webapi/client.py", line 360, in generate_content
    raise APIError(
gemini_webapi.exceptions.APIError: Failed to generate contents. Invalid response data received. Client will try to re-initialize on next request.

**Comment by foremtehan** [comment] 2024-08-09 09:40
here's the log:

```
[["wrb.fr",null,null,null,null,[8]],["di",71],["af.httprm",70,"-6335023805056531313",5]]
INFO:     172.27.0.5:55058 - "POST /generate HTTP/1.1" 500 Internal Server Error
2024-08-09 09:39:56.877 | DEBUG    | gemini_webapi.client:start_auto_refresh:252 - Cookies refreshed. New __Secure-1PSIDTS: None
2024-08-09 09:39:57.016 | DEBUG    | gemini_webapi.client:generate_content:359 - Invalid response: )]}'
```

**Comment by Mvkbesteu** [comment] 2024-08-09 16:13
how could we fix this?

**Comment by HanaokaYuzu** [comment] 2024-08-09 17:56
> here's the log, looks like it couldn't refresh the cookie it's None
> 
> ```
> [["wrb.fr",null,null,null,null,[9,null,[["type.googleapis.com/assistant.boq.bard.application.BardErrorInfo",[1060]]]]],["di",133],["af.httprm",132,"-953864994699850116",5]]
> 2024-08-09 10:01:43.533 | DEBUG    | gemini_webapi.client:start_auto_refresh:252 - Cookies refreshed. New __Secure-1PSIDTS: None
> 2024-08-09 10:01:43.636 | DEBUG    | gemini_webapi.client:generate_content:359 - Invalid response: )]}'
> ```

`Cookies refreshed. New __Secure-1PSIDTS: None` is not an error. Just means cookies are recently refreshed. 

You should include the invalid response text in the last entry. If this:
```
[["wrb.fr",null,null,null,null,[9,null,[["type.googleapis.com/assistant.boq.bard.application.BardErrorInfo",[1060]]]]],["di",133],["af.httprm",132,"-953864994699850116",5]]
```
was the full response text you got, it indicates there was a server error on Google side and likely there's nothing we can do.

**Comment by ephemeral8997** [comment] 2024-08-10 09:31
That's all we could find in the console. I don't really see any relevant information, but this happens when the error occurs.
[log.log](https://github.com/user-attachments/files/16569082/log.log)

**Comment by HanaokaYuzu** [comment] 2024-08-10 19:59
> That's all we could find in the console. I don't really see any relevant information, but this happens when the error occurs. [log.log](https://github.com/user-attachments/files/16569082/log.log)

Could you follow instructions [here](https://github.com/HanaokaYuzu/Gemini-API/issues/30#issuecomment-2276278996) and try again? In the latest version invalid response body will be logged under debug mode.

**Comment by ephemeral8997** [comment] 2024-08-11 07:34
Ah, I see. I sat the log level to INFO by accident, my apologies.
```py
2024-08-11 09:30:25.980 | DEBUG    | gemini_webapi.client:generate_content:359 - Invalid response: )]}'                                                                                                                                                                                                                                                     [["wrb.fr",null,null,null,null,[8]],["di",63],["af.httprm",63,"-7995575725882360630",1]]                                                                                      
```
Clearly it's kinda same as foremtehan's, a server error.

**Comment by foremtehan** [comment] 2024-08-11 09:30
My suspicion is that it is looking for a different cookie value (after a while), which it cannot find, and as a result, it logs out/expires the cookie.

I already have an account logged in on a firefox browser and have never had a problem.

**Comment by HanaokaYuzu** [comment] 2024-08-12 19:53
> My suspicion is that it is looking for a different cookie value (after a while), which it cannot find, and as a result, it logs out/expires the cookie.
> 
> I already have an account logged in on a firefox browser for normal use case, and have never had a problem.

Sorry but that's not the case. By default cookies are scheduled to be refreshed periodically on purpose to prevent from expiring. We don't know what's actually running behind the scenes, but this error hardly ever happens on my side, so it shouldn't be caused by this package.

**Comment by HanaokaYuzu** [comment] 2024-09-11 03:50
It comes out that there's some kinds of rate limiting mechanism. Got the same error when send request too frequently (~10 requests in one minute), but error disappears pretty soon. 

Mark as won't fix due to randomness and infrequency.

**Closed by HanaokaYuzu** 2024-09-11 03:50 UTC
Labels: bug

**Comment by v67bruno** [comment] 2025-08-15 22:36
> It comes out that there's some kinds of rate limiting mechanism. Got the same error when send request too frequently (~10 requests in one minute), but error disappears pretty soon.
> 
> Mark as won't fix due to randomness and infrequency.

I'm having the same error, with a 10s (~6RPM) interval between requests. The error stopped when I increased the interval to 60s (1RPM).

**Comment by qinshuang1998** [comment] 2025-09-16 09:24
this should be Gemini side's behavior, but there seems to be some kind of pattern.
