### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable while generating images

### ISSUE THREAD

**Issue by onur222** [HanaokaYuzu/Gemini-API#18] opened 2024-05-31 07:50 UTC
`  File "/gemini_webapi/client.py", line 370, in <listcomp>
    url=image[0][3][3],
        ~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable`

I receive this error while running this code:

`    


    async def main():
        client = GeminiClient(proxies=None)
        # Create Layout

        response = await client.generate_content("Generate some pictures of cats")
        print(response)

    asyncio.run(main())
`

**Comment by HanaokaYuzu** [comment] 2024-05-31 16:56
Cannot reproduce. Does this happen every time or randomly?

**Comment by onur222** [comment] 2024-06-07 08:35
I happens every time. 
The code can produce images but links to those images are not returned.
I can see the images on https://gemini.google.com/app

I also can produce images on https://gemini.google.com/app with the same prompt.

**Comment by FuseFairy** [comment] 2024-08-01 03:19
I have same issue.

**Comment by HanaokaYuzu** [comment] 2024-08-01 06:04
Unfortunately this error never happens on my side and I'm not able to debug it without the response body you got. Guess that for some reason response structure can be different by account or region. 

Needs someone with basic python debugging skill to set a breakpoint [here](https://github.com/HanaokaYuzu/Gemini-API/blob/871faa1fc86d2fb0084b254b4424623e807042b0/src/gemini_webapi/client.py#L386) and find out the valid indexes (or simply print out and send the full `condidate` object to me).

https://github.com/HanaokaYuzu/Gemini-API/blob/871faa1fc86d2fb0084b254b4424623e807042b0/src/gemini_webapi/client.py#L386-L403

**Comment by HanaokaYuzu** [comment] 2024-09-11 03:41
Fixed in #34

**Closed by HanaokaYuzu** 2024-09-11 03:41 UTC
Labels: bug
